### ISSUE TITLE
Add audio

### ISSUE THREAD

**Issue by Cat-Ion** [Cheeseness/hidden-star#3]
I'm going to be working on adding some audio to the game and want to use this issue to track things I should add.

Background music:
- Basic stuff (start, stop, switch (after track has finished), each with fading)
- Looping (n times)
- Callbacks for when a track has finished?

Ideas for sound effects
- Just plain playback, with callback when finished?
- Playback after delay
- Play at random intervals, could be implemented with callback + delay

**Comment by Cat-Ion** [comment]
I think as soon as #6 is merged, this issue can be closed, unless there's anything else we consider necessary.

**Comment by Cheeseness** [comment]
Woo! I think we've hit all the planned deliverables here. Nice work :)
